CMS_HOST: studio.local.openedx.io
CMS_OAUTH2_SECRET: ylR7e3mEhDuJHpcThptDdK5P
CONTACT_EMAIL: yosephaabate@gmail.com
ENABLE_HTTPS: false
ID: P8FFhN3ulbkHnshtwqAlRSRk
INDIGO_ACCENT_COLOR: '#C9A84C'
INDIGO_PRIMARY_COLOR: '#6F2DBD'
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEAzIZ+Vx2LdSDkKkO85GlAOEZTsx3NwS+FpRnJkuBeMZXrSQhF

  5ki+3gVBVZa1wd+mxF29SZbcLuKaz2HKeQHeXFF/9VPTlBx9GJkOUnOUI0w4bBg4

  fmvLKbBYNf4Tl6MtpZnTDTIapYBUE+XVPKvW5rwGNScQQ3Ry5o7bmVrTg6RwtDKo

  wVzcJq3WPLx8s8m3oD6bc8qikLlkB+U/w4JaY146mY6F8pJthWuQ5h+GY0AH4M7F

  zGMO0Fz1t5rucvfQQtvzOkuuOEdN55KQpggg6dxxHXb1KuPti3zgbTHoLPJ4tlIH

  D7x5r/nXX9ZThkMBZbbqPY7HR/xu+ctSKXsVoQIDAQABAoIBAAO2yKUcJmThJP6M

  3EmLLR82fPktfCe/JUSMuMyy2AgLS354DNWmLhff2V5YnD5oAWYrB/ul1oPQEfDM

  kzfGQkGLufS4bfDwYV/Ksfw6oMLRNMw29oHqcwIL05a/qV87V4Ikjmzsszfcmi5C

  MfiSC+cEzKGvBuI8M2TTHNsSl4EiOUOzMS2WdWAXxy/BwDT3mWWqqm9qODWy/dTB

  VHua1sG4lb94oBjuDX/E1BhT9s3g1Hjuo8tn+BdOFIucsD5MLKxgAlGdLKDSncug

  5wesYUX8caHOtmp9SvUh9KldeDJGNeeSOWDBJorPy6YG/er+dUPCQ9FilGURX65L

  sZ3mB0ECgYEA1GI6PzuVr57JRU0LteCmnNUjFyKc0gFxE9laaTaJpEjG+DvFZILk

  eWZJm+wOn63xxjSwMzJHAPN1PpDsCCTPGLZsQeVuaA+52IlbsgGzGo4P82YXsDHV

  WmP8+efj1flFLZRNI5IW4GrNWAJcAwtd+J0LuTe7uuhjd9InQ4DocGECgYEA9ocg

  BnVacbly/uPOSALpsyCnUpUpFRUr5htZetc/2R7CUIt01Vs9HgTVEj67zchjTxEm

  Rkg7EiBU9mmNUC6tOv8Y5ssTM25dBSLNOUfZDYNMbAX18hQtH//kIb28dm47xzsG

  VNZ16/zfHt3Hw/MbWPWewlf/ebKh4tL+2GylrUECgYEAwlH5jz96ToxPBWxgCZI5

  f4d3qsRNjcwp5QpasadnunuoKRmvGq60Uusm8FXEb49chohQqxcWZiVbIdrBSxY6

  sha+6G/+W5H/7cKHtk/dyq8uovnHNLvzxNd1cEYebPm8tN5a0e/ppH2z0hGelF6D

  JWSzhE0dI/9aexg6OoYopiECgYEArV7/5arYDUxXE+wPINNzmLapFUmy15HJCo1H

  Uz1XOJEKJGy+oGEGzTqmwar+lkyLkopD+X9Ik4nLVnOKns4Eo43M7Fn6SdwebMM5

  wkPF4Fvq/bj/atxHk854mEX/6OXDAmx/GmCsE2cFXoanuyUXoWsy2AfcsbAvav3p

  nThjF0ECgYB0pCjJgYuQymUTIrw4vwaNh2LRTfZYVuELVN00FQDC8aK7IEEAwdR1

  2CQvJRZmFEhPiJG7LaTiTfs70uL8bfXkizZrPkki34ozWbB+0N0MK54k0/Gw7xhx

  FYYhoFPrLOfUzXhe5x8sLmhfr5nJd/rzIHX4VNc4bmcBmRuSykVwJw==

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.openedx.io
MEILISEARCH_API_KEY: 476c6e2e3ed7ddbf6cd4c6e87d1053c1bf0602ed0a372fb6068ec1ff009a8865
MEILISEARCH_API_KEY_UID: 96c0ddb2-7fe8-438d-b420-c655bf0e388e
MEILISEARCH_MASTER_KEY: TxYdMbMpAOytzRmcQ7cIeb9c
MYSQL_ROOT_PASSWORD: o5PwFWVx
OPENEDX_MYSQL_PASSWORD: aNr0cAAd
OPENEDX_SECRET_KEY: 6NPSaEfJbgiajtQXnkQG5JmU
PLATFORM_DESCRIPTION: AI-Powered Learning for Africa
PLATFORM_NAME: AfroLMS
PLUGINS:
- indigo
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
